name: bloom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mime: ^1.0.0
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2
  flutter_cache_manager:
  simple_animations: ^3.1.1
  flutter_easyloading: ^3.0.0
  carousel_pro: ^1.0.0
  flutter_swiper : ^1.1.6
  carousel_slider: ^3.0.0
  badges: ^2.0.1
  rxdart: ^0.27.1
  dio: ^4.0.0
  stripe_sdk: ^5.0.0-nullsafety.0
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^2.0.6
  firebase_core:
  firebase_auth:
  firebase_messaging: ^10.0.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.0
  google_sign_in: ^5.0.4
  uuid: ^3.0.4
  flutter_facebook_auth: ^3.4.0
  jiffy: ^4.1.0
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^9.0.0
  fluttertoast: ^8.0.7
  custom_radio: ^0.1.2
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.0.0
  page_transition: ^2.0.2
  connectivity: ^3.0.6
  data_connection_checker: ^0.3.4
  email_validator: ^2.0.1
  image_picker: ^0.7.5+3
  file_picker: ^3.0.2+2
  intl: ^0.17.0
  flutter_html:
  url_launcher:
  fluttercontactpicker: ^4.4.0
  flutter_local_notifications: ^6.0.0
  intl_phone_number_input: ^0.7.0+2
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.4.0
  html_editor_enhanced: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fb-black.png
    - assets/fb.png
    - assets/git.png
    - assets/google_plus.png
    - assets/twitter.png
    - assets/slider/
    - assets/notifications/
    - assets/payment_icon/
    - assets/user_profile/
    - assets/

  fonts:
    - family: Francois One
      fonts:
        - asset: fonts/FrancoisOne-Regular.ttf
          weight: 400
    - family: Alatsi
      fonts:
        - asset: fonts/Alatsi-Regular.ttf
          weight: 400
    - family: Kaushan Script
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400